export const FINANCE_FETCH = 'FINANCE_FETCH'
export const DEPOSIT_FETCH = 'DEPOSIT_FETCH'
export const CARS_FETCH = 'CATEGORIES_FETCH'
export const CARS_STORE= 'CARS_STORE';
export const CARS_UPDATE = 'CARS_UPDATE'

export const SENT_DEFAULT_VALUE_TO_DIALOG ='SENT_DEFAULT_VALUE_TO_DIALOG'
export const SHOW_CAR_REGISTRATION_MODAL = 'SHOW_CAR_REGISTRATION_MODAL'
export const SHOW_BANK_ACCOUNT_SETTER = 'SHOW_BANK_ACCOUNT_SETTER'

//finance constants
export const PAYMENT_FETCH = 'PAYMENT_FETCH'
export const WITHDRAWAL_FETCH = 'WITHDRAWAL_FETCH'
export const SHOW_WITHDRAWAL_REQUEST = 'SHOW_WITHDRAWAL_REQUEST'
export const STORE_WITHDRAWAL ='STORE_WITHDRAWAL'
export const STORE_DRIVER = 'STORE_DRIVER'

